### ISSUE TITLE
Format not recognized

### ISSUE THREAD

**Issue by Isengo1989** [mheap/frontmatter-json-schema-action#6]
I came across the [format](https://json-schema.org/understanding-json-schema/reference/string#format)  in JSON schema, sadly it does not get recognized. Is this related to a definition here ?

```
    "authors": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "email"
      }
    },
```

```
/node_modules/ajv/dist/vocabularies/format/format.js:63
                throw new Error(unknownMsg());
                      ^

Error: unknown format "email" ignored in schema at path "#/properties/authors/items"
    at unknownFormat (/node_modules/ajv/dist/vocabularies/format/format.js:63:23)
    at validateFormat (/node_modules/ajv/dist/vocabularies/format/format.js:50:1[7](https://github.com/shopware/academy-contents/actions/runs/12181120918/job/33977003615#step:5:8))
    at Object.code (/node_modules/ajv/dist/vocabularies/format/format.js:22:13)
    at keywordCode (/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/node_modules/ajv/dist/compile/codegen/index.js:56[8](https://github.com/shopware/academy-contents/actions/runs/12181120918/job/33977003615#step:5:9):18)
    at iterateKeywords (/node_modules/ajv/dist/compile/validate/index.js:21[9](https://github.com/shopware/academy-contents/actions/runs/12181120918/job/33977003615#step:5:10):9)
    at groupKeywords (/node_modules/ajv/dist/compile/validate/index.js:200:13)
    at /node_modules/ajv/dist/compile/validate/index.js:192:13
```

**Comment by Isengo1989** [comment]
Seems like format is not included per default in ajv

Anything against if I add it like shown here @mheap ?

https://ajv.js.org/guide/formats.html

Could also add options as action inputs to define which ones should be active:

https://github.com/ajv-validator/ajv-formats?tab=readme-ov-file#options

**Comment by mheap** [comment]
I'm open to adding it by default. No need to make it configurable for now
